server:
  port: 8001
spring:
  application:
    name: microservicio-productos
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:productosdb
    username: sa
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect